[project]
name = "holidays-kr"
version = "0.1.0"
description = "Holiday calendar for Republic of Korea"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icalendar>=6.3.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
]
