name: Build Base Image

on:
  push:
    paths:
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'Dockerfile'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/daehyeoni/holidays-kr/holiday-updater-base:latest
