name: Update Holiday Data

on:
  schedule:
    - cron: '0 0,2,4,6,8 * * 1-5'  # UTC time (KST-9)
  workflow_dispatch:

jobs:
  update-holidays:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and run Docker container
      env:
        HOLIDAY_API_KEY: ${{ secrets.HOLIDAY_API_KEY }}
      run: |
        docker buildx build \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
          --load \
          -t holiday-updater .
        docker run --rm \
          -e HOLIDAY_API_KEY=${HOLIDAY_API_KEY} \
          -v ${GITHUB_WORKSPACE}:/app \
          holiday-updater

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Check for changes
      id: check-changes
      run: |
        if [[ -n $(git status -s) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push if changed
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git commit -m "Update holiday data"
        git push

    - name: Trigger deploy workflow
      if: steps.check-changes.outputs.changes == 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: holiday-update
